### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [ranjanistic/sesscook#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by ranjanistic** [comment]
Hey @geopic!  Thanks for your recommendation. I'm not much familiar with TS, therefore yes, I'd be glad if you could do that.

**Comment by geopic** [comment]
Great, I'll start on it now
